Feature/implement grape api
wave49192/book-review-exercise pull request #8
Opened 2024-09-04 03:01 UTC by wave49192

implemented
- book and reviews api endpoint

2024-09-05 08:38 UTC, numin123 requested changes
What about unit tests for new API

2024-09-05 08:45 UTC, siripoom-datawow commented on app/api/v1/books_api.rb
> +        optional :per_page, type: Integer, desc: "Number of books per page"
please give default value for page and per_page krub

2024-09-05 08:45 UTC, siripoom-datawow commented on app/api/v1/books_api.rb
> +        book = Book.find(params[:id])
if you use `find` it will raise error if not found 
then please use `rescue `ActiveRecord::RecordNotFound` 
or use `find_by` || `where` instead

2024-09-05 08:45 UTC, siripoom-datawow commented on app/api/v1/reviews_api.rb
> +            book = Book.find(params[:book_id])
I see many method use book
then we might use it as attribute krub
```
def book do
@book ||= Book.find(params[:book_id])
end
```

2024-09-05 08:45 UTC, siripoom-datawow commented on app/api/v1/reviews_api.rb
> +                end
too many else if kub
it correct but really not clean
Instead we can use guard technique
```
book = Book.find_by(id: id)
return   error!({ message: "Book not found" }, 404) if book.blank?

and so on
```

2024-09-05 08:54 UTC, numin123 commented on app/api/v1/reviews_api.rb
> +            book = Book.find(params[:book_id])
Active record they already do as work well so we do not need to add the cache for query @siripoom-datawow

2024-09-05 09:18 UTC, kaiitoon commented on app/api/v1/books_api.rb
> +        })
this params can move to method  as `book_params` and use that method instead (in create and update )

2024-09-05 09:18 UTC, kaiitoon commented on app/api/v1/books_api.rb
> +        book = Book.find(params[:id])
Like Kaophun said in get api before

2024-09-05 09:20 UTC, kaiitoon commented
You can use `route_param :id do` cover `put get delete` api

2024-09-06 03:48 UTC, wave49192 commented
> What about unit tests for new API

I will do do it in separated branch

2024-09-06 04:41 UTC, merged